# -*- coding: utf-8 -*-
"""Tugas_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J3EhaqLidpUl-FYDRt5DqAo5xPar5REj
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

np.random.seed(42)

jumlah_data = 500

ipk = np.random.normal(3.0, 0.4, jumlah_data)
ipk = np.clip(ipk, 2.0, 4.0)

kehadiran = np.random.normal(80, 12, jumlah_data)
kehadiran = np.clip(kehadiran, 40, 100)

jam_belajar = np.random.normal(15, 7, jumlah_data)
jam_belajar = np.clip(jam_belajar, 0, 40)

organisasi = np.random.choice(['Aktif', 'Tidak Aktif'], jumlah_data, p=[0.4, 0.6])
penghasilan_ortu = np.random.choice(['Rendah', 'Menengah', 'Tinggi'], jumlah_data, p=[0.3, 0.5, 0.2])
jenis_kelamin = np.random.choice(['L', 'P'], jumlah_data)
beasiswa = np.random.choice(['Ya', 'Tidak'], jumlah_data, p=[0.25, 0.75])

skor = (-3
        + 4 * ((ipk - 2) / 2)
        + 3 * ((kehadiran - 40) / 60)
        + 1.5 * (jam_belajar / 40)
        + np.random.normal(0, 1.0, jumlah_data))

peluang_lulus = 1 / (1 + np.exp(-skor))
lulus_tepat_waktu = np.where(np.random.rand(jumlah_data) < peluang_lulus, 'Ya', 'Tidak')

data = pd.DataFrame({
    'IPK': ipk.round(2),
    'Kehadiran': kehadiran.round(1),
    'Jam_Belajar': jam_belajar.round(1),
    'Organisasi': organisasi,
    'Penghasilan_Ortu': penghasilan_ortu,
    'Jenis_Kelamin': jenis_kelamin,
    'Status_Beasiswa': beasiswa,
    'Lulus_Tepat_Waktu': lulus_tepat_waktu
})

kolom_numerik = ['IPK', 'Kehadiran', 'Jam_Belajar']
for kolom in kolom_numerik:
    baris_kosong = np.random.choice(data.index, size=int(0.05 * jumlah_data), replace=False)
    data.loc[baris_kosong, kolom] = np.nan

data.to_csv('mahasiswa_lulus.csv', index=False)

data.head()

print("Cek missing value:")
print(data.isnull().sum())
print()

for kolom in kolom_numerik:
    median_kolom = data[kolom].median()
    data[kolom] = data[kolom].fillna(median_kolom)

print("Setelah diisi:")
print(data.isnull().sum())

encoder_organisasi = LabelEncoder()
encoder_gender = LabelEncoder()
encoder_beasiswa = LabelEncoder()
encoder_target = LabelEncoder()

data['Organisasi_enc'] = encoder_organisasi.fit_transform(data['Organisasi'])
data['Jenis_Kelamin_enc'] = encoder_gender.fit_transform(data['Jenis_Kelamin'])
data['Status_Beasiswa_enc'] = encoder_beasiswa.fit_transform(data['Status_Beasiswa'])


urutan_penghasilan = {'Rendah': 0, 'Menengah': 1, 'Tinggi': 2}
data['Penghasilan_Ortu_enc'] = data['Penghasilan_Ortu'].map(urutan_penghasilan)

data['Target'] = encoder_target.fit_transform(data['Lulus_Tepat_Waktu'])  # Tidak=0, Ya=1

fitur_yang_dipakai = ['IPK', 'Kehadiran', 'Jam_Belajar', 'Organisasi_enc',
                      'Penghasilan_Ortu_enc', 'Jenis_Kelamin_enc', 'Status_Beasiswa_enc']

X = data[fitur_yang_dipakai]
y = data['Target']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Data latih: {len(X_train)} baris")
print(f"Data uji  : {len(X_test)} baris")

model_dt3 = DecisionTreeClassifier(max_depth=3, random_state=42)
model_dt3.fit(X_train, y_train)
prediksi_dt3 = model_dt3.predict(X_test)

model_dt_full = DecisionTreeClassifier(max_depth=None, random_state=42)
model_dt_full.fit(X_train, y_train)
prediksi_dt_full = model_dt_full.predict(X_test)

model_nb = GaussianNB()
model_nb.fit(X_train, y_train)
prediksi_nb = model_nb.predict(X_test)

print("Tiga model udah selesai dilatih.")

def cek_performa(y_asli, y_prediksi, nama):
    akurasi = accuracy_score(y_asli, y_prediksi)
    presisi = precision_score(y_asli, y_prediksi)
    recall = recall_score(y_asli, y_prediksi)
    f1 = f1_score(y_asli, y_prediksi)

    print(f"== {nama} ==")
    print(f"Akurasi   : {akurasi:.3f}")
    print(f"Precision : {presisi:.3f}")
    print(f"Recall    : {recall:.3f}")
    print(f"F1-Score  : {f1:.3f}")
    print()

    return {'Model': nama, 'Akurasi': akurasi, 'Precision': presisi,
            'Recall': recall, 'F1-Score': f1}

hasil_semua_model = []
hasil_semua_model.append(cek_performa(y_test, prediksi_dt3, "Decision Tree (depth=3)"))
hasil_semua_model.append(cek_performa(y_test, prediksi_dt_full, "Decision Tree (depth=None)"))
hasil_semua_model.append(cek_performa(y_test, prediksi_nb, "Naive Bayes"))

tabel_hasil = pd.DataFrame(hasil_semua_model)
tabel_hasil

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
semua_prediksi = [prediksi_dt3, prediksi_dt_full, prediksi_nb]
judul = ['DT (depth=3)', 'DT (depth=None)', 'Naive Bayes']

for ax, pred, t in zip(axes, semua_prediksi, judul):
    cm = confusion_matrix(y_test, pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=['Tidak', 'Ya'], yticklabels=['Tidak', 'Ya'])
    ax.set_title(t)
    ax.set_xlabel('Prediksi')
    ax.set_ylabel('Aktual')

plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=300, bbox_inches='tight')
plt.show()

plt.figure(figsize=(18, 8))
plot_tree(model_dt3, feature_names=fitur_yang_dipakai,
          class_names=['Tidak', 'Ya'], filled=True, rounded=True, fontsize=9)
plt.title("Decision Tree (max_depth=3)")
plt.savefig('decision_tree.png', dpi=300, bbox_inches='tight')
plt.show()

metrik = ['Akurasi', 'Precision', 'Recall', 'F1-Score']
posisi_x = np.arange(len(metrik))
lebar_bar = 0.25

plt.figure(figsize=(10, 6))
for i, baris in tabel_hasil.iterrows():
    plt.bar(posisi_x + i * lebar_bar, baris[metrik].values, lebar_bar, label=baris['Model'])

plt.xticks(posisi_x + lebar_bar, metrik)
plt.ylabel('Skor')
plt.title('Perbandingan Performa 3 Model')
plt.ylim(0, 1.1)
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.savefig('perbandingan_model.png', dpi=300, bbox_inches='tight')
plt.show()

X_test_ulang = X_test.reset_index(drop=True)
y_test_ulang = y_test.reset_index(drop=True)
pred_series = pd.Series(prediksi_dt3)

mask_salah = y_test_ulang != pred_series
data_salah = X_test_ulang[mask_salah].copy()
data_salah['Aktual'] = y_test_ulang[mask_salah].map({0: 'Tidak', 1: 'Ya'})
data_salah['Prediksi'] = pred_series[mask_salah].map({0: 'Tidak', 1: 'Ya'})

print("5 contoh data yang salah diprediksi:")
data_salah.head(5)

kasus_uji = pd.DataFrame({
    'IPK': [3.8],
    'Kehadiran': [50],
    'Jam_Belajar': [10],
    'Organisasi_enc': [0],
    'Penghasilan_Ortu_enc': [1],
    'Jenis_Kelamin_enc': [0],
    'Status_Beasiswa_enc': [0]
})[fitur_yang_dipakai]

hasil_dt3 = model_dt3.predict(kasus_uji)[0]
hasil_nb = model_nb.predict(kasus_uji)[0]
peluang_nb = model_nb.predict_proba(kasus_uji)[0]

print("Simulasi: IPK tinggi, kehadiran rendah")
print(f"Decision Tree bilang : {'Ya' if hasil_dt3 == 1 else 'Tidak'}")
print(f"Naive Bayes bilang   : {'Ya' if hasil_nb == 1 else 'Tidak'}")
print(f"Probabilitas NB [Tidak, Ya]: {peluang_nb.round(3)}")

data_salah.head(5).to_csv('analisis_error_5data.csv', index=False)